# Generated by Django 4.2.4 on 2023-08-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='SiteRegister',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
