# Generated by Django 4.2.4 on 2023-08-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_globalsettings_siteregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='broc_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
